common: &common
  adapter: postgresql
  min_messages: warning
  username: <%= 'brandon' %>
  password: <%= 'correcthorsestablebattery' %>
  prepared_statements: false

development:
  <<: *common
  database: mathhammer_dev

test:
  <<: *common
  database: mathhammer_test

production:
  <<: *common
  database: handshake
